spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: han_spring_rest
    password: Sohappy212

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      indent-output: true

