spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_db
    username: root
    password: Sohappy212@

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

